
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./Uploads:/app/Uploads
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - CHROMA_HOST=http://chroma:8000
      - GOOGLE_API_KEY=AIzaSyADFkHbHJCNg1du_RaVU5A-UmHnIKf3ZmU
    depends_on:
      - mongo
      - chroma


  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/data
    environment:
      - CHROMA_PERSIST_DIR=/data
      - PRESIST_DIR=/data
      - ALLOW_PERSISTENCE=true
      - ALLOW_RESET=false


volumes:
  mongo_data:
  chroma_data:
